#!/usr/bin/env python3
"""
Build assets for the Services view (8 service pages) and Clients view
(our-work brand heroes + homepage featured cards) from the "GM images" drop.

Outputs:
  images/heroes/<slug>.webp          hero banners (max 2000px, q80)
  images/heroes/thumbs/<slug>.webp   card-sized (max 900px, q78)
  images/services/<slug>.webp        gallery thumbs for Automation/Retail-Audit extras (max 640px)
  scripts/assets-manifest.json       hero + service-gallery + featured-card mapping for HTML wiring

Service galleries mostly REUSE the already-built images/work/<brand>/thumbs/*.webp
(generated by build_work_gallery.py); this script only adds the photos that
don't live in a brand folder (Automation, Retail Audit) plus all hero/card images.
"""
import json
import shutil
from pathlib import Path
from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "GM images" / "Website Content"
FEAT = SRC / "Featured Image"
HEROES = ROOT / "images" / "heroes"
SERVICES = ROOT / "images" / "services"
WORK_DATA = ROOT / "js" / "work-gallery-data.js"


def save_webp(src_path, dest, max_side, quality):
    with Image.open(src_path) as im:
        im = ImageOps.exif_transpose(im)
        if im.mode in ("RGBA", "P", "LA"):
            im = im.convert("RGB")
        w, h = im.size
        if max(w, h) > max_side:
            if w >= h:
                im = im.resize((max_side, round(h * max_side / w)), Image.LANCZOS)
            else:
                im = im.resize((round(w * max_side / h), max_side), Image.LANCZOS)
        dest.parent.mkdir(parents=True, exist_ok=True)
        im.save(dest, "WEBP", quality=quality, method=6)
    return dest


# ---- HERO / CARD SOURCES ----------------------------------------------------
# slug -> source image (relative to "Website Content")
HERO_SRC = {
    # Service heroes (4 named have Featured Images; others use a strong on-theme shot)
    "svc-merchandising":   "Cocacola/Merchandising - Cocacola/IMG_8184.jpg",
    "svc-field-activations": "Featured Image/Activations/_MG_0016.jpg",
    "svc-dynamic-roadshows": "Cocacola/Cocacola Activations/Predator Road Shows/GM-18.jpg",
    "svc-events-management": "Cocacola/Cocacola Activations/World Free Style Football Event/GM-50.jpg",
    "svc-field-automation-surveys": "Featured Image/Automation/ACT_9726_1.jpg",
    "svc-retail-audit":    "Retail Audit/ACT_9722_1.jpg",
    "svc-distribution-sales": "Shell Vivo/Merchandising - Shell Vivo/GM-23.jpg",
    "svc-strategy":        "Strategy/ACT_9722_1.jpg",
    # Client heroes (our-work brand sections) + homepage cards
    "client-cocacola":  "Featured Image/Cocacola/IMG_8257.jpg",
    "client-shell":     "Featured Image/Shell Vivo Energies/Copy of GM-16.jpg",
    "client-unilever":  "Featured Image/Unilever/IMG_8938.jpg",
    "client-ubl":       "Featured Image/Uganda Breweries LTD/IMG_3486.jpg",
    "client-latitude":  "Featured Image/Latitude Chocolate/IMG_9177.jpg",
}

# ---- SERVICE GALLERY SELECTION ---------------------------------------------
# Each service page shows 9 gallery thumbs. We pull from the brand pool by
# campaign title / type, and (for automation/retail-audit) from local extras.
EXTRA_SRC = {  # service-folder photos that aren't in any brand folder
    "automation-1": "Automation/ACT_9711_1.jpg",
    "automation-2": "Automation/ACT_9716_1.jpg",
    "retail-audit-1": "Retail Audit/ACT_9722_1.jpg",
    "retail-audit-2": "Retail Audit/ACT_9726_1.jpg",
    "strategy-1": "Strategy/ACT_9722_1.jpg",
    "strategy-2": "Strategy/ACT_9726_1.jpg",
}


def load_pool():
    code = WORK_DATA.read_text(encoding="utf-8")
    code = code.replace("const galleryData", "globalThis_x")  # neutralize
    # crude parse: extract the JSON array
    start = code.index("[")
    arr = json.loads(code[start:code.rindex("]") + 1])
    pool = []
    for b in arr:
        for im in b["images"]:
            pool.append({"brand": b["id"], "thumb": im["thumb"],
                         "type": im["type"], "title": im["title"]})
    return pool


def interleave(pool):
    """Round-robin the pool across brands so galleries show a mix, not one brand."""
    by_brand = {}
    for p in pool:
        by_brand.setdefault(p["brand"], []).append(p)
    order, lists = [], list(by_brand.values())
    i = 0
    while any(lists):
        lst = lists[i % len(lists)]
        if lst:
            order.append(lst.pop(0))
        i += 1
        if i > len(pool) * 2:
            break
    return order


def pick(pool, predicate, n, used):
    # filter first, THEN interleave, so a single brand can't monopolise a gallery
    candidates = interleave([p for p in pool if predicate(p) and p["thumb"] not in used])
    out = candidates[:n]
    for p in out:
        used.add(p["thumb"])
    return out


def main():
    for d in (HEROES, SERVICES):
        if d.exists():
            shutil.rmtree(d)

    manifest = {"heroes": {}, "services": {}, "cards": {}}

    # Heroes (full + card thumb)
    for slug, rel in HERO_SRC.items():
        full = save_webp(SRC / rel, HEROES / f"{slug}.webp", 2000, 80)
        thumb = save_webp(SRC / rel, HEROES / "thumbs" / f"{slug}.webp", 900, 78)
        manifest["heroes"][slug] = f"images/heroes/{slug}.webp"
        print(f"hero {slug:32} {full.stat().st_size//1024}KB")
    manifest["cards"] = {  # homepage featured cards -> card-sized client heroes
        k.replace("client-", ""): f"images/heroes/thumbs/{k}.webp"
        for k in HERO_SRC if k.startswith("client-")
    }

    # Service-extra gallery thumbs (Automation / Retail Audit)
    extra = {}
    for slug, rel in EXTRA_SRC.items():
        save_webp(SRC / rel, SERVICES / f"{slug}.webp", 640, 72)
        extra[slug] = f"images/services/{slug}.webp"

    # Service galleries (9 thumbs each). thumbs are relative to site root;
    # service pages live in /services/ so HTML will prefix "../".
    pool = load_pool()

    def merch(p): return p["type"] == "merchandising"
    def act(p): return p["type"] == "activation"

    galleries = {}

    used = set()
    galleries["field-activations"] = [p["thumb"] for p in pick(pool, act, 9, used)]

    used = set()
    galleries["merchandising"] = [p["thumb"] for p in pick(pool, merch, 9, used)]

    used = set()
    road_titles = {"Predator Roadshows", "Rwenzori Marathon", "Rwenzori Marathon Launch",
                   "Fuel On The Go", "Rimula Oils"}
    g = pick(pool, lambda p: p["title"] in road_titles, 9, used)
    g += pick(pool, act, 9 - len(g), used)
    galleries["dynamic-roadshows"] = [p["thumb"] for p in g]

    used = set()
    event_titles = {"World Freestyle Football", "Roast & Rhyme", "Coke Studio",
                    "Shell Expo", "Fanta Movie Time", "Heads Up", "Hamper Promo"}
    g = pick(pool, lambda p: p["title"] in event_titles, 9, used)
    g += pick(pool, act, 9 - len(g), used)
    galleries["events-management"] = [p["thumb"] for p in g]

    used = set()
    g = pick(pool, merch, 6, used) + pick(pool, act, 3, used)
    galleries["distribution-sales"] = [p["thumb"] for p in g]

    used = set()
    # strategy: lead with the office strategy-session photos, then a cross-brand mix
    g = pick(pool, lambda p: p["brand"] == "cocacola", 3, used)
    g += pick(pool, lambda p: p["brand"] == "unilever", 2, used)
    g += pick(pool, lambda p: p["brand"] == "shell", 2, used)
    galleries["strategy"] = [extra["strategy-1"], extra["strategy-2"]] + [p["thumb"] for p in g]

    used = set()
    g = [extra["automation-1"], extra["automation-2"]]
    g += [p["thumb"] for p in pick(pool, act, 7, used)]
    galleries["field-automation-surveys"] = g

    used = set()
    g = [extra["retail-audit-1"], extra["retail-audit-2"]]
    g += [p["thumb"] for p in pick(pool, merch, 7, used)]
    galleries["retail-audit"] = g

    manifest["services"] = galleries

    (ROOT / "scripts" / "assets-manifest.json").write_text(
        json.dumps(manifest, indent=2), encoding="utf-8")
    print("\nService gallery sizes:",
          {k: len(v) for k, v in galleries.items()})
    print("Wrote scripts/assets-manifest.json")


if __name__ == "__main__":
    main()
